name = "LAMBS Danger"
prefix = "lambs"
author = "LAMBS Dev Team"
sigversion = 3
version = "2.3.3"
reuse_private_key = true
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE",
    "readme.txt",
    "readme.md"
]
include = ["./include"]

keyname = "{{prefix}}_danger_{{version}}"
signame = "{{prefix}}_danger_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip @LambsDanger"
]

[header_exts]
version= "{{git \"id 8\"}}"
