name: Stringtable

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: Install Python packages
      run: |
        pip3 install wheel
        pip3 install setuptools
        pip3 install pygithub
        pip3 install pygithub3
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Update Translation issue
      if: github.repository == 'com/nk3nny/LambsDanger' && ! contains(github.event.head_commit.message, '[ci skip]')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 tools/stringtableDeploy.py
